import { useEffect, useMemo, useState } from 'react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Skeleton } from '@/components/ui/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { academicApi, type AcademicYear, type StudentAcademicRecord } from '@/services/api';
import { useAuth } from '@/contexts/AuthContext';
import { AlertTriangle, Pencil, Search, Users } from 'lucide-react';

type RosterRow = StudentAcademicRecord & { name: string; english_name?: string; enrollment_cohort: string; student_status: string };

export default function AcademicRecordsPage() {
  const { user } = useAuth();
  const [years, setYears] = useState<AcademicYear[]>([]); const [yearId, setYearId] = useState(''); const [rows, setRows] = useState<RosterRow[]>([]); const [query, setQuery] = useState(''); const [editing, setEditing] = useState<RosterRow | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [refresh, setRefresh] = useState(0);
  const canEdit = user?.role === 'admin' || user?.role === 'staff' || user?.role === 'supervisor';
  useEffect(() => { let cancelled = false; academicApi.getYears().then((items) => { if (!cancelled) { setYears(items); setYearId((current) => current || items.find((item) => item.status === 'active')?.id || items[0]?.id || ''); } }).catch((reason) => { if (!cancelled) setError(reason instanceof Error ? reason.message : '加载失败'); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);
  useEffect(() => { if (!yearId) return; let cancelled = false; academicApi.getStudentRecordRoster(yearId).then((items) => { if (!cancelled) setRows(items); }).catch((reason) => { if (!cancelled) setError(reason instanceof Error ? reason.message : '加载失败'); }); return () => { cancelled = true; }; }, [yearId, refresh]);
  const filtered = useMemo(() => { const keyword = query.trim().toLowerCase(); return keyword ? rows.filter((row) => `${row.name} ${row.english_name || ''} ${row.enrollment_cohort}`.toLowerCase().includes(keyword)) : rows; }, [rows, query]);
  const missing = rows.filter((row) => !row.id).length;
  return <div className="flex flex-col gap-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="flex flex-col gap-1"><p className="text-sm font-medium text-primary">学生连续学段</p><h1 className="text-2xl font-semibold tracking-tight">年级与资格阶段档案</h1><p className="text-sm text-muted-foreground">入学届、校内年级和 IGCSE/AS/A Level 是不同概念；本页按学年明确记录，不再混用。</p></div><Select value={yearId} onValueChange={setYearId}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{years.map((year) => <SelectItem key={year.id} value={year.id}>{year.name}</SelectItem>)}</SelectGroup></SelectContent></Select></div>{error && <Alert variant="destructive"><AlertTriangle /><AlertTitle>档案加载失败</AlertTitle><AlertDescription>{error}</AlertDescription></Alert>}<div className="flex flex-col gap-3 rounded-lg border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div className="relative w-full sm:max-w-sm"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索学生或入学届" /></div><div className="flex items-center gap-2 text-sm"><Users className="size-4 text-primary" /><span>{rows.length} 名学生</span><Badge variant={missing > 0 ? 'outline' : 'secondary'}>{missing} 名待补全</Badge></div></div>{loading ? <Skeleton className="h-96 w-full" /> : <div className="overflow-hidden rounded-lg border bg-card"><Table><TableHeader><TableRow><TableHead>学生</TableHead><TableHead>入学届（历史字段）</TableHead><TableHead>本学年年级</TableHead><TableHead>资格阶段</TableHead><TableHead>行政班</TableHead><TableHead>状态</TableHead><TableHead className="text-right">操作</TableHead></TableRow></TableHeader><TableBody>{filtered.map((row) => <TableRow key={row.student_id}><TableCell><div className="flex flex-col gap-0.5"><span className="font-medium">{row.name}</span><span className="text-xs text-muted-foreground">{row.english_name || row.student_id}</span></div></TableCell><TableCell>{row.enrollment_cohort}</TableCell><TableCell>{row.school_grade ? `${row.school_grade}年级` : <Badge variant="outline">待录入</Badge>}</TableCell><TableCell>{row.qualification_stage ? (row.qualification_stage === 'A_LEVEL' ? 'A Level' : row.qualification_stage) : '—'}</TableCell><TableCell>{row.homeroom || '—'}</TableCell><TableCell><Badge variant={row.id ? 'secondary' : 'outline'}>{row.id ? '已配置' : '未配置'}</Badge></TableCell><TableCell className="text-right">{canEdit && <Button variant="ghost" size="sm" onClick={() => setEditing(row)}><Pencil data-icon="inline-start" />{row.id ? '编辑' : '录入'}</Button>}</TableCell></TableRow>)}</TableBody></Table></div>}<EditRecordDialog row={editing} yearId={yearId} onOpenChange={(open) => { if (!open) setEditing(null); }} onSaved={() => { setEditing(null); setRefresh((value) => value + 1); }} /></div>;
}

function EditRecordDialog({ row, yearId, onOpenChange, onSaved }: { row: RosterRow | null; yearId: string; onOpenChange: (open: boolean) => void; onSaved: () => void }) {
  const [grade, setGrade] = useState('9'); const [stage, setStage] = useState<'IGCSE' | 'AS' | 'A_LEVEL'>('IGCSE'); const [homeroom, setHomeroom] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { if (row) { const nextGrade = String(row.school_grade || 9); setGrade(nextGrade); setStage(row.qualification_stage || (Number(nextGrade) <= 10 ? 'IGCSE' : Number(nextGrade) === 11 ? 'AS' : 'A_LEVEL')); setHomeroom(row.homeroom || ''); setError(''); } }, [row]);
  const save = async () => { if (!row) return; setSaving(true); setError(''); try { await academicApi.saveStudentRecord(row.student_id, { academic_year_id: yearId, academic_year_name: '', school_grade: Number(grade) as 9 | 10 | 11 | 12, qualification_stage: stage, homeroom: homeroom || null, status: 'active', notes: null }); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : '保存失败'); } finally { setSaving(false); } };
  return <Dialog open={!!row} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>设置学年学段</DialogTitle><DialogDescription>{row?.name} · 入学届 {row?.enrollment_cohort}。修改本记录不会改动历史成绩和考季数据。</DialogDescription></DialogHeader><FieldGroup><Field><FieldLabel>校内年级</FieldLabel><Select value={grade} onValueChange={(value) => { setGrade(value); setStage(Number(value) <= 10 ? 'IGCSE' : Number(value) === 11 ? 'AS' : 'A_LEVEL'); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup>{[9, 10, 11, 12].map((value) => <SelectItem key={value} value={String(value)}>{value}年级</SelectItem>)}</SelectGroup></SelectContent></Select></Field><Field><FieldLabel>资格阶段</FieldLabel><Select value={stage} onValueChange={(value) => setStage(value as typeof stage)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="IGCSE">IGCSE</SelectItem><SelectItem value="AS">AS</SelectItem><SelectItem value="A_LEVEL">A Level</SelectItem></SelectGroup></SelectContent></Select></Field><Field><FieldLabel htmlFor="homeroom">行政班</FieldLabel><Input id="homeroom" value={homeroom} onChange={(event) => setHomeroom(event.target.value)} placeholder="例如 G9-1" /></Field>{error && <Alert variant="destructive"><AlertTriangle /><AlertDescription>{error}</AlertDescription></Alert>}</FieldGroup><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>取消</Button><Button disabled={saving} onClick={save}>{saving ? '保存中…' : '保存学段档案'}</Button></DialogFooter></DialogContent></Dialog>;
}
